//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.SQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RequestLogEntities : DbContext
    {
        public RequestLogEntities()
            : base("name=RequestLogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int InsertLog(string dateTime, string content)
        {
            var dateTimeParameter = dateTime != null ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(string));
    
            var contentParameter = content != null ?
                new ObjectParameter("Content", content) :
                new ObjectParameter("Content", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLog", dateTimeParameter, contentParameter);
        }
    
        public virtual ObjectResult<GetLog_Result> GetLog(Nullable<long> idOffset)
        {
            var idOffsetParameter = idOffset.HasValue ?
                new ObjectParameter("IdOffset", idOffset) :
                new ObjectParameter("IdOffset", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLog_Result>("GetLog", idOffsetParameter);
        }
    }
}
